apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  labels:
    app: redis
    project: roboshop
    tier: db
spec:
  selector:
    matchLabels:
      app: redis
      project: roboshop
      tier: db
  serviceName: "redis"
  replicas: {{ .Values.statefullSet.replicas }}
  template:
    metadata:
      labels:
        app: redis
        project: roboshop
        tier: db
    spec:
      containers:
      - name: redis
        image: "redis:{{ .Values.statefullSet.imageVersion }}"
        volumeMounts:
        - name: redis
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: redis
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 1Gi
